name: "Discord Bully"
description: "Bully people into fixing failing build. Built specifically for Bedrock Wiki."
inputs:
  webhook:
    description: "discord webhook url without /github"
    required: true
  emoji:
    description: "emoji id after blaming someone"
    required: true
    default: "<:PE_PandaBonk:885395101877166110>"
  title:
    description: "Discord embed title"
    required: true
    default: "Wiki deployment failed"


runs:
  using: "node12"
  main: "index.js"